############################################################################
# Contest 2026 team 008 charging station - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = charging_station
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 2048
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_008_CHARGING_STATION)

MAINSRC = charging_station_main.c

include $(APPDIR)/Application.mk
